[adme]
gnn_atom_enabled = true
gnn_comp_enabled = true
gnn_spacial_enabled = true
mlp_enabled = true

# Increasing layers may or may not improve model performance. It will slow down inference and training.
# We have it lower than idea now to improve speed.


gnn_atom_layers = 1
gnn_comp_layers = 3
# It seems  a higher value here, to a point, is relatively cheap, and produces better results.
gnn_spacial_layers = 7
# It seems  a higher value here, to a point, is relatively cheap, and produces better results.
mlp_layers = 4